### ISSUE TITLE
Issues related to different parameters

### ISSUE THREAD

**Issue by ghost** [Al-th/MVA_TonalStabilization#1]
Hi Dear,
When I run your code for testing. It seems to be the number of errors in your code. Can you help me to sort out these errors? Thanks

**Comment by Al-th** [comment]
Hi.
What are the errors ?

**Comment by alikhan968** [comment]
If you don't mind  can i get your contact number where we can discuss in
detail

On 10 Feb 2018 10:41 p.m., "Al-th" <notifications@github.com> wrote:

Hi.
What are the errors ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Al-th/MVA_Project_TonalStabilization/issues/1#issuecomment-364674966>,
or mute the thread

**Comment by ghost** [comment]
I made some changing in your code. Like in tonalStablization module 
vidFramesp = uint8(zeros(height,width,3,nbFrames));  **here i pass argument nbFrames**
%%
vidFramesp(:,:,:,1:100) = vidFrames(:,:,:,1:100);
vidFramesp(:,:,:,101:300) = vidFrames(:,:,:,101:300);   **change value here**
%nbFrames = 200;                                                 **make comment this line**
vidFrames = vidFramesp;
%%
after running your code and these changing it shows this error

**

> Computing corrected frames 9.966667e+01
> Computing corrected frames 100
> Undefined function or variable 'frameInit'.
> 
> Error in tonalStabilisation (line 96)
> frame = double(vidFrames(:,:,:,frameInit+1));

**

**Comment by ghost** [comment]
If I initialized **frameInit with zero** then the next error which appears looks like this...

> Computing adjustmentFrame 0.3Attempted to access Ai(1,81,1); index out of bounds because size(Ai)=[60,80,3].
> 
> Error in computeAdjustmentFrame (line 46)
>             A_init(i,j,1) = Ai(i,j,1) + (labFrame(i,j,1) - labFrame2(i,j,1));

**Comment by Al-th** [comment]
Sorry but I do not give my personal information online.

Coming back to your errors : 

- vidFramesp is a temporary variable where you put the video you want to process. It is used to reduce the size of the image sequence that was initially read.
- From what I do recall, the block starting line 23 is sufficient to apply the full tonal stabilization. I should have removed everything after line 93 as this is old code that is not needed. 

Once the full processing has taken place, you can find the "corrected" movie by using the command  "implay(frameCorrected)"

Best

**Comment by ghost** [comment]
Thanks for the reply, I have just reviewed your updated files and now it's working. Thanks for great help
